source 'https://rubygems.org'

gem 'activerecord'
gem 'aws-sdk', '~> 3'
gem 'httpclient', '~> 2.7', '>= 2.7.1'
gem 'mysql2'
gem 'rake'
gem 'sinatra'
gem 'standalone_migrations'
group :test do
  gem 'rspec-rails', '~> 3.0'
end

